[env:esp32-poe-iso]
platform = espressif32
board = esp32-poe-iso
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7

[env:native]
platform = native
test_framework = unity
build_flags = -DNATIVE_TEST
test_build_src = true
